# Generated by Django 4.2.6 on 2023-10-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brokers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=512, verbose_name='Full Name')),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('iscompany', models.BooleanField(default=False, verbose_name='Is Company')),
            ],
            options={
                'verbose_name': 'Broker',
                'verbose_name_plural': 'Brokers',
            },
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Max Length 128 symbols', max_length=128, verbose_name='Title')),
                ('subject', models.CharField(help_text='Max Length 128 symbols', max_length=128, verbose_name='Subject')),
                ('context', models.TextField(verbose_name='Context')),
            ],
            options={
                'verbose_name': 'Mail Template',
                'verbose_name_plural': 'Mail Templates',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('chat_id', models.IntegerField(unique=True, verbose_name='Chat ID')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'TelegramUser',
                'verbose_name_plural': 'TelegramUsers',
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Name')),
                ('vehicle_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Vehicle ID')),
                ('current_location', models.CharField(blank=True, max_length=256, null=True, verbose_name='Current Location')),
                ('destination', models.CharField(blank=True, default='-', max_length=256, null=True, verbose_name='Destination')),
                ('eta', models.CharField(blank=True, max_length=256, null=True, verbose_name='ETA')),
                ('planned_time', models.DateTimeField(blank=True, null=True, verbose_name='Planned Time')),
                ('eta_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='ETA Status')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Status')),
                ('fuel', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fuel Percent')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('live_share', models.URLField(blank=True, null=True, verbose_name='Live Share')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated At')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.brokers', verbose_name='Broker')),
            ],
            options={
                'verbose_name': 'Update',
                'verbose_name_plural': 'Updates',
            },
        ),
    ]
